#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd

while IFS=':' read -r username password uid gid info home shell; do
	echo "the user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < "/etc/passwd"
