#!/usr/bin/env bash
# This script is displaying "Best School" 8 times &  for the 4th loop "bad luck"and disply "good luck" for the 8th loop iteration

x=0
while (( x<10 ))
do
	if (( x==3 ))
	then
		echo "bad luck"
	elif (( x==7 ))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( x++ ))
done
